// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA74VZzScsQHQxsc5uUsyixHTCytg5RBeI',
    appId: '1:660882152497:web:997afd809bc4f6ff540910',
    messagingSenderId: '660882152497',
    projectId: 'fir-miner-932a7',
    authDomain: 'fir-miner-932a7.firebaseapp.com',
    storageBucket: 'fir-miner-932a7.appspot.com',
    measurementId: 'G-9CKGMPNZJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzpt1cYGlnyBqIpWqPI49aLeFr2hCNPNU',
    appId: '1:660882152497:android:4561361a1a38403f540910',
    messagingSenderId: '660882152497',
    projectId: 'fir-miner-932a7',
    storageBucket: 'fir-miner-932a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbbF6vB371IEFtUJyWuDAJzzYp0ijh_XY',
    appId: '1:660882152497:ios:b8f0fff45c30d05f540910',
    messagingSenderId: '660882152497',
    projectId: 'fir-miner-932a7',
    storageBucket: 'fir-miner-932a7.appspot.com',
    iosBundleId: 'com.example.firebaseminer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbbF6vB371IEFtUJyWuDAJzzYp0ijh_XY',
    appId: '1:660882152497:ios:b8f0fff45c30d05f540910',
    messagingSenderId: '660882152497',
    projectId: 'fir-miner-932a7',
    storageBucket: 'fir-miner-932a7.appspot.com',
    iosBundleId: 'com.example.firebaseminer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA74VZzScsQHQxsc5uUsyixHTCytg5RBeI',
    appId: '1:660882152497:web:604b6d54d1123d16540910',
    messagingSenderId: '660882152497',
    projectId: 'fir-miner-932a7',
    authDomain: 'fir-miner-932a7.firebaseapp.com',
    storageBucket: 'fir-miner-932a7.appspot.com',
    measurementId: 'G-2WGGWPH7LY',
  );

}